//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIO()
        {
            this.FUNCIONARIO1 = new HashSet<FUNCIONARIO>();
            this.HISTORIAL_RESOLUCIONES = new HashSet<HISTORIAL_RESOLUCIONES>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.SOLICITUD1 = new HashSet<SOLICITUD>();
        }
    
        public string RUT { get; set; }
        public string RUT_EVALUADOR { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime FECHA_CREACION { get; set; }
        public System.DateTime FECHA_MODIFICACION { get; set; }
        public decimal ESTADO { get; set; }
        public decimal ID_ROL { get; set; }
        public decimal ID_UNIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO1 { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO2 { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_RESOLUCIONES> HISTORIAL_RESOLUCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD1 { get; set; }
    }
}
