//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOTIVO
    {
        public decimal ID_MOTIVO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_TIPOSOLICITUD { get; set; }
    
        public virtual TIPO_SOLICITUD TIPO_SOLICITUD { get; set; }
    }
}
