//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_RESOLUCIONES
    {
        public decimal ID_RESOLUCION { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public string RUT_EMISOR { get; set; }
        public string UNIDAD { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
    }
}
