//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortafolioWeb.WebServiceRH {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WebServiceRH")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceRH.IAsistencia")]
    public interface IAsistencia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsistencia/GetAntiguedad", ReplyAction="http://tempuri.org/IAsistencia/GetAntiguedadResponse")]
        int GetAntiguedad(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsistencia/GetAntiguedad", ReplyAction="http://tempuri.org/IAsistencia/GetAntiguedadResponse")]
        System.Threading.Tasks.Task<int> GetAntiguedadAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsistencia/GetAsistencia", ReplyAction="http://tempuri.org/IAsistencia/GetAsistenciaResponse")]
        bool GetAsistencia(string rut, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsistencia/GetAsistencia", ReplyAction="http://tempuri.org/IAsistencia/GetAsistenciaResponse")]
        System.Threading.Tasks.Task<bool> GetAsistenciaAsync(string rut, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsistencia/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAsistencia/GetDataUsingDataContractResponse")]
        PortafolioWeb.WebServiceRH.CompositeType GetDataUsingDataContract(PortafolioWeb.WebServiceRH.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAsistencia/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAsistencia/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PortafolioWeb.WebServiceRH.CompositeType> GetDataUsingDataContractAsync(PortafolioWeb.WebServiceRH.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAsistenciaChannel : PortafolioWeb.WebServiceRH.IAsistencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsistenciaClient : System.ServiceModel.ClientBase<PortafolioWeb.WebServiceRH.IAsistencia>, PortafolioWeb.WebServiceRH.IAsistencia {
        
        public AsistenciaClient() {
        }
        
        public AsistenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsistenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsistenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsistenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAntiguedad(string rut) {
            return base.Channel.GetAntiguedad(rut);
        }
        
        public System.Threading.Tasks.Task<int> GetAntiguedadAsync(string rut) {
            return base.Channel.GetAntiguedadAsync(rut);
        }
        
        public bool GetAsistencia(string rut, System.DateTime fecha) {
            return base.Channel.GetAsistencia(rut, fecha);
        }
        
        public System.Threading.Tasks.Task<bool> GetAsistenciaAsync(string rut, System.DateTime fecha) {
            return base.Channel.GetAsistenciaAsync(rut, fecha);
        }
        
        public PortafolioWeb.WebServiceRH.CompositeType GetDataUsingDataContract(PortafolioWeb.WebServiceRH.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PortafolioWeb.WebServiceRH.CompositeType> GetDataUsingDataContractAsync(PortafolioWeb.WebServiceRH.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
